# Name(s) : Alex Lopez, Anthony Tran, Glen Lee

# Description: sets up docker network to allow connection between client and master nodes + manages scraper nodes

version: '3'
services: # Defines containsers to be created
  master:
    build:
      context: ./master # Path for Dockerfile for building the master service image
    networks:
      - Proj2-distributed-network # Connects to netowrk
    volumes:
      - ./data:/app/data

  node1: # Definition for first scraper node service
    build: 
      context: ./food_network_scraper # Path to Dockerfile for scraper node
    volumes:
      - ./data:/app/data
    networks:
      - Proj2-distributed-network

  client: # Definition for client service
    build: 
      context: ./client # Path to Dockerfile for node
    networks:
      - Proj2-distributed-network

networks:
  Proj2-distributed-network: # Defines custom network
    name: Proj2-distributed-network # Specifies network name
    driver: bridge # Uses bridge driver for Docker networking